name: Build Release manually

on:
  workflow_dispatch:

jobs:
  linux-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Init submodules
        run: git submodule update --init --checkout --recursive

      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: electronuserland/builder:wine
          options: -v ${{ github.workspace }}:/project
          run: |
            npm ci
            npm run build
            npm run bundle:linux

      - name: Save deb artifact
        uses: actions/upload-artifact@v4
        with:
          name: deb-build
          path: |
            dist/*.deb

      - name: Save snap artifact
        uses: actions/upload-artifact@v4
        with:
          name: snap-build
          path: |
            dist/*.snap

      - name: Save AppImage artifact
        uses: actions/upload-artifact@v4
        with:
          name: appimage-build
          path: |
            dist/*.AppImage

  mac-build:
    runs-on: macos-latest

    needs: linux-build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - run: npm ci
      - run: npm run build
      - run: npm run bundle:mac

      - name: Save dmg artifact
        uses: actions/upload-artifact@v4
        with:
          name: dmg-build
          path: |
            dist/*.dmg
